/* eslint-disable react/prop-types */
import html2pdf from "html2pdf.js";
import { useState } from "react";

const ResumeTemplate = ({ data }) => {
  const [loading, setLoading] = useState(false);

  const handlePdf = async () => {
    setLoading(true);
    try {
      const element = document.getElementById("resume-container");

      // Set the options directly
      const options = {
        margin: [0.5, 0.5, 0.5, 0.5],
        filename: "myResume.pdf",
        image: { type: "jpeg", quality: 1 },
        html2canvas: { scale: 3 }, // Increased scale for better quality
        jsPDF: { unit: "in", format: "a4", orientation: "portrait" },
      };

      await html2pdf().set(options).from(element).save();
    } catch (error) {
      console.error("PDF generation failed:", error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div
      id="resume-container" // Ensuring correct ID for html2pdf targeting
      className="p-8 max-w-3xl mx-auto bg-white shadow-lg rounded-lg"
    >
      <h1 className="text-3xl font-bold mb-4 text-center">
        {data?.name || "Name"}
      </h1>
      <p className="mb-2 text-center">
        {data?.email || "Email"} | {data?.phone || "Phone"}
      </p>
      <p className="mb-4 text-center">{data?.address || "Address"}</p>
      <p className="mb-4 text-center">{data?.gender || "Gender"}</p>

      {/* Description Section */}
      <h2 className="text-2xl font-semibold mt-6 mb-2">Description</h2>
      <p className="mb-4">{data?.description || "Description goes here"}</p>

      {/* Education Section */}
      <h2 className="text-2xl font-semibold mt-6 mb-2">Education</h2>
      {data?.education?.length > 0 ? (
        data.education.map((edu, index) => (
          <div key={index}>
            <p className="font-bold">{edu.title || "Title"}</p>
            <p>
              {edu.degree || "Degree"} - {edu.institute || "Institute"},{" "}
              {edu.year || "Year"}
            </p>
          </div>
        ))
      ) : (
        <p className="text-center">Education information not available</p>
      )}

      {/* Skills Section */}
      <h2 className="text-2xl font-semibold mt-6 mb-2">Skills</h2>
      {data?.skills?.length > 0 ? (
        <ul>
          {data.skills.map((skill, index) => (
            <li key={index}>
              {skill.title || "Skill"} - {skill.experience || "Experience"}
            </li>
          ))}
        </ul>
      ) : (
        <p className="text-center">Skills not available</p>
      )}

      {/* Social Links Section */}
      <h2 className="text-2xl font-semibold mt-6 mb-2">Social Links</h2>
      <p>Facebook: {data?.socialLinks?.facebook || "N/A"}</p>
      <p>Twitter: {data?.socialLinks?.twitter || "N/A"}</p>
      <p>LinkedIn: {data?.socialLinks?.linkedin || "N/A"}</p>
      <p>GitHub: {data?.socialLinks?.github || "N/A"}</p>

      {/* Download Button */}
      <button
        onClick={handlePdf}
        className={`mt-6 px-4 py-2 bg-blue text-white font-bold rounded shadow hover:bg-blue-600 transition duration-300 ${
          loading ? "opacity-50 cursor-not-allowed" : ""
        }`}
        disabled={loading}
      >
        {loading ? "Generated By Hiring Staff" : "Download Resume"}
      </button>
    </div>
  );
};

export default ResumeTemplate;
